[window]
padding = { x = 16, y = 16 }
opacity = 0.8
[font]
normal = { family = "SF Mono", style = "Regular" }
bold = { family = "SF Mono", style = "Bold" }
italic = { family = "SF Mono", style = "Italic" }
bold_italic = { family = "SF Mono", style = "Bold Italic" }
size = 11
offset = { x = 0 , y = 2 }
[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.2
